### PR TITLE
Documentation & File Organization Updates

### PR DESCRIPTION
**Pull request by Invarchitect**

### CODE REVIEW

**Comment by arrudagates** [comment]
I would suggest keeping pallet directories to complete lowercase and with `-` instead of `_`: `Pallet_ips` -> `pallet-ips`

**Review by SHA888 — COMMENTED** [review]
Looks good to me.

**Comment by SHA888** [comment]
@Invarchitect @arrudagates After resolving some conflicts on this, I think we could merge it to development branch?

**Comment by S0raWasTaken** [comment]
> @Invarchitect @arrudagates After resolving some conflicts on this, I think we could merge it to development branch?

It might be good to merge after refactoring the main `Cargo.toml`. Merging our push branches should be easy too

**Review by arrudagates — APPROVED** [review]
Tested locally on the node, no further modifications needed over there. Approved and merging.

**Pull request merged**
